package com.virtualworld.easyexpensecontrol.domain.usecase.recurring

import com.virtualworld.easyexpensecontrol.core.util.RecurringDateHelper
import com.virtualworld.easyexpensecontrol.data.model.RecurringTransaction
import com.virtualworld.easyexpensecontrol.data.model.Transaction
import com.virtualworld.easyexpensecontrol.domain.repository.RecurringTransactionRepository
import com.virtualworld.easyexpensecontrol.domain.repository.TransactionRepository
import com.virtualworld.easyexpensecontrol.domain.usecase.transaction.SaveTransactionUseCase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.datetime.Clock
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

class ProcessRecurringTransactionsUseCase(
    private val recurringTransactionRepository: RecurringTransactionRepository,
    private val transactionRepository: TransactionRepository,
    private val saveTransactionUseCase: SaveTransactionUseCase
) {
    suspend operator fun invoke(): List<Transaction> = withContext(Dispatchers.IO) {
        val generated = mutableListOf<Transaction>()
        val today = Clock.System.now()
            .toLocalDateTime(TimeZone.currentSystemDefault())
            .date
        val currentYearMonth = today.year * 100 + today.monthNumber

        recurringTransactionRepository.getAllActive().forEach { template ->
            var lastProcessed = template.lastProcessedYearMonth
            var yearMonth = RecurringDateHelper.nextYearMonth(template.lastProcessedYearMonth)

            while (yearMonth <= currentYearMonth) {
                val year = yearMonth / 100
                val month = yearMonth % 100
                val targetDay = minOf(
                    template.dayOfMonth,
                    RecurringDateHelper.daysInMonth(year, month)
                )
                val dueDate = kotlinx.datetime.LocalDate(year, month, targetDay)

                if (today >= dueDate) {
                    if (transactionRepository.countAutoGeneratedForRecurringInMonth(template.id, yearMonth) == 0) {
                        val transaction = Transaction(
                            type = template.type,
                            amount = template.amount,
                            category = template.categoryId,
                            description = template.description,
                            date = RecurringDateHelper.millisAtStartOfDay(year, month, targetDay),
                            accountId = template.accountId,
                            recurringTransactionId = template.id,
                            isAutoGenerated = true
                        )
                        saveTransactionUseCase.addTransactionWithBudget(transaction)
                        generated += transaction
                    }
                    lastProcessed = yearMonth
                }

                yearMonth = RecurringDateHelper.nextYearMonth(yearMonth)
            }

            if (lastProcessed != template.lastProcessedYearMonth) {
                recurringTransactionRepository.update(
                    template.copy(lastProcessedYearMonth = lastProcessed)
                )
            }
        }

        generated
    }
}
