# This file contains the fastlane.tools configuration
# For a list of all available actions: https://docs.fastlane.tools/actions
# For a list of all available plugins: https://docs.fastlane.tools/plugins/available-plugins

default_platform(:android)

platform :android do

    desc "Build application"
    lane :build do
      gradle(task: "clean assembleDebug")
    end

    desc "Perform Unit tests"
    lane :tests do
      gradle(task: "testDebugUnitTest")
    end

    desc "Perform Instrumented tests"
    lane :ui_tests do
      gradle(
        task: 'clean'
      )
      gradle(
        task: 'assemble',
        build_type: 'Debug'
      )
      gradle(
        task: 'assemble',
        build_type: 'AndroidTest'
      )

    end

end
